# Generated by Django 5.0.6 on 2024-07-09 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_deliveryassignment_status_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('delivery_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.deliverystaff')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignment_history', to='orders.orderhistory')),
            ],
        ),
    ]
