# Generated by Django 5.0.6 on 2024-07-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryassignmenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverystaff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
