# Generated by Django 5.0.6 on 2024-07-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliverystaff_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryassignmenthistory',
            options={'ordering': ['-completed_at']},
        ),
    ]
