# Generated by Django 5.0.6 on 2024-07-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_deliveryassignmenthistory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryassignmenthistory',
            options={},
        ),
    ]
