# Generated by Django 5.0.4 on 2024-06-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
