# Generated by Django 5.0.4 on 2024-06-13 02:04

import advertise.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0002_alter_advertise_description_alter_advertise_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='image',
            field=models.ImageField(upload_to='ads/', validators=[advertise.models.validate_file_extension]),
        ),
    ]
