# Generated by Django 5.0.6 on 2024-06-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='url_name_auth',
            field=models.CharField(blank=True, help_text='The name of the URL pattern for authenticated users', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url_name',
            field=models.CharField(help_text='The name of the URL pattern for unauthenticated users', max_length=100),
        ),
    ]
