# Generated by Django 5.0.6 on 2024-06-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_menuitem_url_name_auth_alter_menuitem_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
