# Generated by Django 5.0.6 on 2024-06-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_menuitem_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('footer_link', models.URLField(blank=True, null=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('copyright_text', models.CharField(max_length=255)),
            ],
        ),
    ]
