# Generated by Django 5.0.6 on 2024-07-01 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_socialmedialink_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMediaLink',
        ),
    ]
