# Generated by Django 5.0.6 on 2024-07-15 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('copyright_text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='home.footer')),
            ],
            options={
                'verbose_name_plural': 'Social Media Links',
            },
        ),
    ]
