# Generated by Django 5.0.6 on 2024-07-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher priority ads will be shown first'),
        ),
    ]
