# Generated by Django 5.0.6 on 2024-07-11 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliverystaff_phone_number'),
        ('userprofile', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='delivery_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliverystaff'),
        ),
    ]
