# Generated by Django 5.0.6 on 2024-07-11 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_notification_delivery_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='delivery_staff',
        ),
    ]
