# Generated by Django 5.0.6 on 2024-07-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_notification_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='order',
        ),
    ]
