# Generated by Django 5.0.6 on 2024-08-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
