# Generated by Django 5.0.6 on 2024-07-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
