# Generated by Django 5.0.6 on 2024-07-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_delete_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
