# Generated by Django 5.0.6 on 2024-07-13 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderhistory_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='ordered_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
