# Generated by Django 5.0.6 on 2024-07-16 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderhistory_ordered_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(choices=[('Banteay Meanchey', 'Banteay Meanchey'), ('Battambang', 'Battambang'), ('Kampong Cham', 'Kampong Cham'), ('Kampong Chhnang', 'Kampong Chhnang'), ('Kampong Speu', 'Kampong Speu'), ('Kampong Thom', 'Kampong Thom'), ('Kampot', 'Kampot'), ('Kandal', 'Kandal'), ('Koh Kong', 'Koh Kong'), ('Kratie', 'Kratie'), ('Mondulkiri', 'Mondulkiri'), ('Phnom Penh', 'Phnom Penh'), ('Preah Vihear', 'Preah Vihear'), ('Prey Veng', 'Prey Veng'), ('Pursat', 'Pursat'), ('Ratanakiri', 'Ratanakiri'), ('Siem Reap', 'Siem Reap'), ('Preah Sihanouk', 'Preah Sihanouk'), ('Stung Treng', 'Stung Treng'), ('Svay Rieng', 'Svay Rieng'), ('Takeo', 'Takeo'), ('Oddar Meanchey', 'Oddar Meanchey'), ('Kep', 'Kep'), ('Pailin', 'Pailin'), ('Tboung Khmum', 'Tboung Khmum')], max_length=50)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Order Addresses',
            },
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderaddress'),
        ),
    ]
