# Generated by Django 5.0.6 on 2024-07-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_delete_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
