# Generated by Django 5.0.6 on 2024-07-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderhistory_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='paypal_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
