# Generated by Django 5.0.6 on 2024-07-26 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_orderhistory_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='paypal_transaction_id',
        ),
    ]
