# Generated by Django 5.0.6 on 2024-07-12 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
