# Generated by Django 5.0.6 on 2024-07-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayspec',
            name='refresh_rate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
