# Generated by Django 5.0.6 on 2024-07-23 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_displayspec_refresh_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='laptopspec',
            name='refresh_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.refreshrate'),
        ),
    ]
