# Generated by Django 5.0.6 on 2024-07-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_stock_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayspec',
            name='resolution',
            field=models.CharField(blank=True, choices=[('HD', 'HD'), ('Full HD', 'Full HD'), ('QHD', 'QHD'), ('4K', '4K')], max_length=100, null=True),
        ),
    ]
